[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:agent]
command=node dist/agent/index.js start
directory=/app
autostart=true
autorestart=true
startretries=10
stopwaitsecs=30
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:server]
command=node dist/server/index.js
directory=/app
environment=PORT="8000"
autostart=true
autorestart=true
startretries=5
stopwaitsecs=15
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:dashboard]
command=/app/docker-dashboard.sh
directory=/app
autostart=true
autorestart=true
startretries=5
stopwaitsecs=15
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
